manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 6862cecf6458bcc70bcec5ca5aac65852be0b671
      path: bsp
    - name: rootfs
      revision: 728d24e5287b1157dc0369aae0f0274051ebc323
      path: rootfs
    - name: tools
      revision: 9fb9cff6401c68605862b68b0606e6947a5ca411
      path: tools
