manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 66e5619f2752444c33637889a8f0d6d3b123e33c
      path: bsp
    - name: rootfs
      revision: 97e7b60ab96c08e1f4b784ed4d477b274656b907
      path: rootfs
    - name: apps
      revision: f000a4f6f9f1e00aea82af11553a97bfad21ec76
      path: rootfs/apps
    - name: tools
      revision: 49ce526d0b0b631b4994195d31479342ba8392ec
      path: tools
