manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 66e5619f2752444c33637889a8f0d6d3b123e33c
      path: bsp
    - name: rootfs
      revision: 0bb7ce46aae21663678a7a1c8d82a0391ad6699b
      path: rootfs
    - name: tools
      revision: 1dd9fc5568d8f6e997645648446fc1a8baa8b251
      path: tools
