manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: git@github.com:nulix
    - name: origin-https
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 89b0eb9fcec86a181d6126e75a4aea3110866714
      path: bsp
    - name: rootfs
      revision: 1ce00c86334498ff024a89c09877204d7b6a58eb
      path: rootfs
    - name: apps
      revision: f000a4f6f9f1e00aea82af11553a97bfad21ec76
      path: rootfs/apps
    - name: tools
      revision: 4092cd21d0079724882080b9e5b08475fa521e88
      path: tools
