manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 66e5619f2752444c33637889a8f0d6d3b123e33c
      path: bsp
    - name: rootfs
      revision: 728d24e5287b1157dc0369aae0f0274051ebc323
      path: rootfs
    - name: tools
      revision: 9fb9cff6401c68605862b68b0606e6947a5ca411
      path: tools
