manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 89b0eb9fcec86a181d6126e75a4aea3110866714
      path: bsp
    - name: rootfs
      revision: 6b7b33d5c24bd40d010cc389e5e878d4a6e6e250
      path: rootfs
    - name: apps
      revision: f000a4f6f9f1e00aea82af11553a97bfad21ec76
      path: rootfs/apps
    - name: tools
      revision: 4092cd21d0079724882080b9e5b08475fa521e88
      path: tools
