manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 66e5619f2752444c33637889a8f0d6d3b123e33c
      path: bsp
    - name: rootfs
      revision: db11bd8a14ced276a21365d9b1836b6300a26872
      path: rootfs
    - name: tools
      revision: 754df4ee8474f183eb8ec7a62e16e186877a5d44
      path: tools
