manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 6862cecf6458bcc70bcec5ca5aac65852be0b671
      path: bsp
    - name: rootfs
      revision: cd5e2c55901a7aba423a4cd92c22ed5922e0b2a5
      path: rootfs
    - name: tools
      revision: 778b2a2858aad2d59ce7a9cd2e46ade136fc08bc
      path: tools
