manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 9dfa667a196d71a89fa53893f8146dc22ea7d8a4
      path: bsp
    - name: rootfs
      revision: c936eeba0de501f66235dc9f555fa89642281401
      path: rootfs
    - name: tools
      revision: 37b010e17b8b64f145570470441c622dcdc8a825
      path: tools
