manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 9dfa667a196d71a89fa53893f8146dc22ea7d8a4
      path: bsp
    - name: rootfs
      revision: 860a27795edbbfe15356781d749d69b4fad38038
      path: rootfs
    - name: tools
      revision: 837abeb5e315f1b366586b53e63e2e3b9482df42
      path: tools
