manifest:
  defaults:
    remote: origin

  remotes:
    - name: origin
      url-base: git@github.com:nulix
    - name: origin-https
      url-base: https://github.com/nulix

  projects:
    - name: bsp
      revision: 66e5619f2752444c33637889a8f0d6d3b123e33c
      path: bsp
    - name: rootfs
      revision: 16e71366f1d596c8b32e135da7860f21135fe4bd
      path: rootfs
    - name: apps
      revision: f000a4f6f9f1e00aea82af11553a97bfad21ec76
      path: rootfs/apps
    - name: tools
      revision: 4c145653703b2989d63ff9adc440bfaf9d8f580b
      path: tools
